### PR TITLE
Add offsets to commands

### PR DESCRIPTION
**Pull request by rk3rn3r**
- cleanup duplicate code in commands
- make global access with Java easier with common parent classes
- all commands should have their startOffset and endOffset so that replication can properly continue

### CODE REVIEW

**Comment by rk3rn3r** [comment]
Hey @leonchen83!
I needed access to startOffset and endOffset for commands, so I made some changes to apply that to your code.
I'm really looking forward to your feedback!

Best,
René

**Comment by leonchen83** [comment]
@rk3rn3r 
`GenericKeyValueCommand`and `GenericKeyCommand` are really good idea.
`GenericCommand with `startOffset` and `endOffset` need further considered.
I will change the related code about  `startOffset` and `endOffset` in `offset` branch. if done, please help review code.

**Comment by rk3rn3r** [comment]
Thank you! Sure, I will review once you are ready!

**Comment by rk3rn3r** [comment]
There are some more commands that could use some adjusting to aggregate some duplicate code. I just did it for key[] and byte[] and for introducing offsets.

**Comment by leonchen83** [comment]
@rk3rn3r 
hi I submit a [commit](https://github.com/leonchen83/redis-replicator/commit/f9ab9e7d36140e64b143661cf8db226c124829d5) about command offset.
after this commit. we can get all `Event`'s offset. not only `Command` offset. and get the offset when reading aof file and rdb file.
usage as following
```java

AbstractEvent e = (AbstractEvent)event;
Tuple2<Long, Long> tuple = e.getContext().getOffsets();
```

**Comment by rk3rn3r** [comment]
That's pretty awesome.
Thank you so much! <3

**Comment by leonchen83** [comment]
we need some time to test above commit(manual test, integration test, add new test case and etc).
after about 2 weeks, we can release v3.3.0

**Pull request merged**
